### ISSUE TITLE
Unused class variables

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/openGemini-client-python#44]
https://github.com/openGemini/opengemini-client-python/blob/c96d4eb1f6f43460d88aef27ccae8b7681f8abe5/opengemini_client/client_impl.py#L68-L71

Here's why it's important to declare class variables that don't need to be shared and aren't being used. Instead of using instance variables directly

**Comment by hezhangjian** [comment]
I revisited the code, and I found that only the `config` field is not used in other methods. While I don't object to removing it, I believe it's acceptable to keep it here for now.

**Comment by wolfbolin** [comment]
**Class variables** will be share in **all** instance. It is not a declaration of **instance variables**. The two are fundamentally different in the way they are used

**Comment by hezhangjian** [comment]
I see. That's a problem we must solve until release 0.1.0. Would you be willing to assist in fixing this issue?

**Comment by hezhangjian** [comment]
closed by #49
