### ISSUE TITLE
Multi-threaded problems

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/openGemini-client-python#47]
https://github.com/openGemini/opengemini-client-python/blob/c96d4eb1f6f43460d88aef27ccae8b7681f8abe5/opengemini_client/client_impl.py#L89-L92

The `increment` and `get_value` operations are not simultaneous, and the behavior may not be as expected when concurrent.
Also, monotonically incrementing numbers and taking modulo operations is not a reasonable way to rotate.

**Comment by hezhangjian** [comment]
closed by #58
