### ISSUE TITLE
PEP 249

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/openGemini-client-python#48]
May be we can rewrite opengemini client based on [PEP 249](https://www.python.org/dev/peps/pep-0249/)

This is a common database API specification. Using this specification can help us benefit from tools that are common to the community.

For example, we can use [DBUtils](https://webwareforpython.github.io/DBUtils/main.html) to implement secure connection pooling instead of implementing it ourselves.

**Comment by hezhangjian** [comment]
Indeed, PEP 249 is a widely adopted standard, and many databases have implemented it. However, OpenGemini is a time series database with specific requirements and use cases that differ from traditional relational databases. At this stage, I am not certain of the direct benefits this adaptation would bring to our project. For connection pool, I guess we can leverage requetes library?

Could you please propose more detailed ideas and clarify how you envision this implementation? This will help us better understand the potential advantages and challenges.

**Comment by wolfbolin** [comment]
PEP249 provides a jdbc-like database connection specification. It mainly contains standard control methods for configuration, connections, and cursors.

PEP249 does not limit the type of database connection to relational databases. In my opinion, only the connection methods and standard SQL interactions are defined. It also provides good extended definitions for two-phase commits and exception handling.

I note that opengemini is also a database that uses SQL interaction, which means it can use the PEP249 specification at a small cost. If opengemini-client is independently coded for multi-threading and multi-process security. This means that developers will need to use separate structures for security and connection utilization in their design. At the same time, we will not be able to benefit from other extensions that follow this specification.

May be I can use it like:
```python
from opengemini-client as opengemini
from dbutils.pooled_db import PooledDB


app_config = {
    "gemini": {},
    "pool": {},
}
gemini_pool = PooledDB(creator=opengemini, **app_config["gemini"], **app_config["pool"])


# In function
conn = gemini_pool.connection()
cursor = conn.cursor()
cursor.execute("INSERT weather,location=us-midwest temperature=%s", args=[tmp])
conn.commit()  # or Autocommit
```

**Comment by hezhangjian** [comment]
@zhiheng123 Did you miss to comment the closed reason?

**Comment by zhiheng123** [comment]
Yes, I did miss the comment. I would like to add:
This is not in line with [the design of our SDK](https://github.com/openGemini/openGemini.github.io/blob/main/src/guide/develop/client_design.md), and we have no plans to support this feature.
