### ISSUE TITLE
Compare with Enum

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/openGemini-client-python#61]
https://github.com/openGemini/opengemini-client-python/blob/bf6e0c178d6d1c62d71d31583b78d7677c8a4a18/opengemini_client/client_impl.py#L100

Is it batter to compare with `AuthType.PASSWORD` ?
`if self.config.auth_config.auth_type == AuthType.PASSWORD:`

**Comment by hezhangjian** [comment]
Thanks for your report, it's fixed in #63
